import {
  Geist,
  Geist_Mono,
  Poppins,
  Comforter_Brush,
  DM_Sans,
} from "next/font/google";
import "./globals.css";
import Providers from "@/components/share/provider";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Toaster } from "sonner";
import { UserProvider } from "@/components/share/UserProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-poppins",
});
const comforterBrush = Comforter_Brush({
  weight: "400", 
  subsets: ["latin"],
  variable: "--font-comforter-brush",
});

const dmSans = DM_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-dm-sans",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${dmSans.variable} ${comforterBrush.variable} antialiased `}
      >
        <UserProvider>
          <Providers>
            <div>
              <div className="">
                <Toaster richColors position="top-center" />
                <main>{children}</main>
              </div>
            </div>
          </Providers>
        </UserProvider>
      </body>
    </html>
  );
}
